version: "3.7"

volumes:
  rabbitmq-data:
  posts-db-data:
  auth-db-data:

services:

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
    restart: unless-stopped


  gateway:
    build: .
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/Copenhagen
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
      - JWT_HMAC_SECRET=secret
      - PORT=5000
    restart: unless-stopped


  ## Posts ##
  posts:
    image: imagehostmad/posts:latest
    environment:
      - TZ=Europe/Copenhagen
      - MONGO_CONN_URI=mongodb://mongo:27017/?readPreference=primary&ssl=false
      - RABBITMQ_CONN_URI=amqp://guest:guest@rabbitmq:5672/
      - JWT_HMAC_SECRET=secret
    restart: unless-stopped

  mongo:
    image: mongo:latest
    volumes:
      - posts-db-data:/data/db
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
  ## End of Posts ##



  ## Authentication ##
  authentication:
    image: imagehostmad/authentication:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DB=authentication
      - MYSQL_PORT=3306
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_HOST=rabbitmq
    restart: unless-stopped

  mysql:
    image: mysql:8
    command: --init-file /data/application/init.sql
    volumes:
      - auth-db-data:/var/lib/mysql
      - .compose-service-files/auth-init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=authentication
    restart: always
  ## End of Authentication ##