version: "3.7"

volumes:
  rabbitmq-data:
  mongo-data:
  mysql-data:


services:

  ## WORKING
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
    restart: unless-stopped


  ## WORKING
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - ${PWD}/.compose-service-files/mongo-entrypoint.js:/docker-entrypoint-initdb.d/entrypoint.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_HOST=mongodb
    command: [--auth]
    restart: unless-stopped


  ## WORKING
  mysql:
    image: mysql:8
    command: --init-file /data/application/init.sql
    volumes:
      #- mysql-data:/var/lib/mysql
      -  ${PWD}/.compose-service-files/mysql-init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=1234
    restart: unless-stopped


  ## WORKING
  gateway:
    build: .
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/Copenhagen
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
      - JWT_HMAC_SECRET=secret
      - PORT=5000
    restart: unless-stopped


  ## WORKING
  posts:
    image: imagehostmad/posts:latest
    #build: ../Posts
    environment:
      - TZ=Europe/Copenhagen
      - MONGO_CONN_URI=mongodb://root:rootpassword@mongo:27017/?readPreference=primary&ssl=false
      - RABBITMQ_CONN_URI=amqp://guest:guest@rabbitmq:5672/
      - MONGO_HOST=mongo
      - MONGO_USER=root
      - MONGO_PASS=rootpassword
      - AMQP_USER=guest
      - AMQP_PASS=guest
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_VHOST=/
      - JWT_HMAC_SECRET=secret
    restart: unless-stopped


  ## WORKING
  authentication:
    image: imagehostmad/authentication:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DB=authentication
      - MYSQL_PORT=3306
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_HOST=rabbitmq
    restart: unless-stopped


  ## WORKING
  likes:
    image: imagehostmad/likes:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=root
      - MYSQL_DB=Likes
      - MYSQL_PORT=3306
      - MYSQL_HOST=mysql
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_HOST=rabbitmq
    restart: unless-stopped


  ## WORKING
  tags:
    image: imagehostmad/tags:latest
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672
      - MYSQL_USER=dbadmin
      - MYSQL_PASSWORD=1234
      - MYSQL_HOST=mysql
      - SECRET_KEY=secret
    restart: unless-stopped


  ## WORKING
  comments:
    image: imagehostmad/comments:main
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MYSQL_DATABASE=commentdb
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    restart: unless-stopped


  # WORKING
  userscripts:
    image: imagehostmad/user-scripts:latest
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=rootpassword
      - MONGO_HOST=mongo
    restart: unless-stopped



  imagestorage:
    image: imagehostmad/imagestorage:main
    #build: https://github.com/MSDO-ImageHost/ImageStorage.git
    environment:
      - DB_USER=""
      - DB_PASSWORD=""
      #- DB_URI=jdbc:sqlite:test.sqlite
      #- DB_DRIVER=org.sqlite.JDBC
      - DB_URI=jdbc:mysql://root:1234@mysql:3306/imagestorage
      - DB_DRIVER=????
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
    restart: unless-stopped
