version: "3.7"

volumes:
  rabbitmq-data:
  mongo-data:
  mysql-data:
  img-data:

services:
  vscode:
    image: qmcgaw/nodedevcontainer
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Copenhagen
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
      - JWT_HMAC_SECRET=secret
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - 3000:3000
      - 5000:5000
    entrypoint: zsh -c "while sleep 1000; do :; done"


  rabbitmq:
    extends:
      file: ../docker-compose.yml
      service: rabbitmq

  mysql:
    extends:
      file: ../docker-compose.yml
      service: mysql

  mongo:
    extends:
      file: ../docker-compose.yml
      service: mongo

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always

  posts:
    extends:
      file: ../docker-compose.yml
      service: posts

  authentication:
    extends:
      file: ../docker-compose.yml
      service: authentication

  likes:
    extends:
      file: ../docker-compose.yml
      service: likes

  tags:
    extends:
      file: ../docker-compose.yml
      service: tags

  comments:
    extends:
      file: ../docker-compose.yml
      service: comments

  userscripts:
    extends:
      file: ../docker-compose.yml
      service: userscripts

  imagestorage:
    extends:
      file: ../docker-compose.yml
      service: imagestorage