version: "3.7"

volumes:
  rabbitmq-data:
  posts-db-data:
  auth-db-data:

services:
  vscode:
    image: qmcgaw/nodedevcontainer
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Copenhagen
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
      - JWT_HMAC_SECRET=secret
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - 3000:3000
      - 5000:5000
    entrypoint: zsh -c "while sleep 1000; do :; done"


  rabbitmq:
    extends:
      file: ../docker-compose.yml
      service: rabbitmq


  posts:
    extends:
      file: ../docker-compose.yml
      service: posts
  mongo:
    extends:
      file: ../docker-compose.yml
      service: mongo



  authentication:
    extends:
      file: ../docker-compose.yml
      service: authentication
  mysql:
    extends:
      file: ../docker-compose.yml
      service: mysql