name: Build Docker images

on:
  push:
    branches: [ master ]

jobs:
  unified-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the unified Docker image
      run: docker build -f Dockerfile .